export const CATEGORY_META = {
  info: {
    label: "案内",
    color: "#d94b3d",
  },
  food: {
    label: "飲食",
    color: "#2a8c63",
  },
  exhibition: {
    label: "展示",
    color: "#386ef2",
  },
  event: {
    label: "催し",
    color: "#d59a1a",
  },
  lounge: {
    label: "休憩",
    color: "#6e5494",
  },
};

function area(x, y, width, height) {
  return { x, y, width, height };
}

function guideDetail({ group, classification, title, room, page, note }) {
  return [
    group ? `団体: ${group}` : null,
    classification ? `分類: ${classification}` : null,
    title ? `企画: ${title}` : null,
    room ? `場所: ${room}` : null,
    note ? `補足: ${note}` : null,
  ]
    .filter(Boolean)
    .join("\n");
}

function multiGuideDetail(items, note) {
  const blocks = items.map((item) => guideDetail(item));
  if (note) {
    blocks.push(`補足: ${note}`);
  }

  return blocks.join("\n\n");
}

function point({
  id,
  label,
  category,
  area: pointArea,
  pixel,
  labelOffset,
  summary,
  detail,
}) {
  return {
    id,
    label,
    category,
    ...(pointArea ? { area: pointArea } : {}),
    pixel:
      pixel ??
      (pointArea
        ? {
            x: pointArea.x + pointArea.width / 2,
            y: pointArea.y + pointArea.height / 2,
          }
        : undefined),
    ...(labelOffset ? { labelOffset } : {}),
    summary: summary ?? detail,
    detail,
  };
}

export const FLOOR_DATA = [
  {
    id: "1F",
    label: "1階",
    headline: "受付と特別棟企画のフロア",
    description:
      "受付、キッチンカー、中庭の案内に加えて、和室・CALL教室・多目的室1・調理室・F1AB の企画を選択できます。",
    imageUrl: new URL("../assets/floors/1F.png", import.meta.url).href,
    dimensions: { width: 1133, height: 580 },
    anchor: { x: 534, y: 392 },
    slabColor: "#d9b870",
    points: [
      point({
        id: "reception",
        label: "受付",
        category: "info",
        area: area(191, 110, 42, 72),
        summary: "来場受付",
        detail: guideDetail({
          group: "文化祭本部",
          classification: "案内",
          title: "来場受付",
          room: "受付",
          note: "通用門側から入った来場者の受付です。",
        }),
      }),
      point({
        id: "courtyard-ticket",
        label: "中庭",
        category: "event",
        area: area(537, 286, 150, 180),
        summary: "3年劇チケット配布",
        detail: guideDetail({
          group: "3年演劇",
          classification: "案内",
          title: "観劇チケット配布",
          room: "中庭",
          note: "各公演の30分前より、特別教室棟1階中庭でチケットを配布します。",
        }),
      }),
      point({
        id: "food-ticket",
        label: "食券用テント",
        category: "food",
        area: area(777, 34, 180, 46),
        summary: "飲食券の案内",
        detail: guideDetail({
          group: "文化祭本部",
          classification: "飲食案内",
          title: "食券販売・案内",
          room: "食券用テント",
          note: "視聴覚室の飲食スペースやキッチンカー利用の前に確認する案内です。",
        }),
      }),
      point({
        id: "kitchen-car",
        label: "キッチンカー",
        category: "food",
        area: area(854, 178, 155, 176),
        summary: "屋外飲食販売",
        detail: guideDetail({
          group: "キッチンカー",
          classification: "飲食",
          title: "屋外販売",
          room: "キッチンカーエリア",
          note: "購入品は視聴覚室の飲食スペースまたは指定場所で利用します。",
        }),
      }),
      point({
        id: "japanese-room",
        label: "和室",
        category: "food",
        area: area(354, 195, 128, 72),
        summary: "茶道部「喫茶去」",
        detail: guideDetail({
          group: "茶道部",
          classification: "食品",
          title: "喫茶去",
          room: "和室",
          page: "18ページ",
        }),
      }),
      point({
        id: "call-room",
        label: "CALL教室",
        category: "exhibition",
        area: area(354, 294, 128, 68),
        summary: "コンピュータ研究会「コン研 神ゲーDX」",
        detail: guideDetail({
          group: "コンピュータ研究会",
          classification: "成果発表",
          title: "コン研 神ゲーDX〜自作コンテスト〜",
          room: "CALL教室",
          page: "21ページ",
        }),
      }),
      point({
        id: "multipurpose-1",
        label: "多目的室1",
        category: "event",
        area: area(354, 404, 128, 70),
        summary: "演劇部 特別公演",
        detail: guideDetail({
          group: "演劇部",
          classification: "演劇",
          title: "文化祭用特別公演",
          room: "多目的室1",
          page: "18ページ",
        }),
      }),
      point({
        id: "cooking-room",
        label: "調理室",
        category: "food",
        area: area(666, 106, 148, 64),
        summary: "家庭部「お菓子売ります」",
        detail: guideDetail({
          group: "家庭部",
          classification: "食品",
          title: "お菓子売ります",
          room: "調理室",
          page: "18ページ",
        }),
      }),
      point({
        id: "f1ab",
        label: "F1AB",
        category: "event",
        area: area(723, 514, 150, 82),
        summary: "2年6組「江戸百怪談」",
        detail: guideDetail({
          group: "2年6組",
          classification: "お化け屋敷",
          title: "江戸百怪談",
          room: "F1AB",
          page: "15ページ",
        }),
      }),
    ],
  },
  {
    id: "2F",
    label: "2階",
    headline: "視聴覚室と3年企画のフロア",
    description:
      "視聴覚室の飲食スペース、図書室、多目的室2、PTA コーナーと、3-1 から 3-8 の企画を選択できます。",
    imageUrl: new URL("../assets/floors/2F.png", import.meta.url).href,
    dimensions: { width: 555, height: 494 },
    anchor: { x: 278, y: 250 },
    slabColor: "#8fb5eb",
    points: [
      point({
        id: "audio-visual-room",
        label: "視聴覚室",
        category: "food",
        area: area(358, 77, 92, 72),
        summary: "キッチンカー購入品 飲食スペース",
        detail: guideDetail({
          group: "その他",
          classification: "その他",
          title: "キッチンカー購入品飲食スペース",
          room: "視聴覚室",
          note: "キッチンカーで購入した飲食物の利用スペースです。",
        }),
      }),
      point({
        id: "library",
        label: "図書室",
        category: "exhibition",
        area: area(154, 103, 88, 84),
        summary: "図書委員会「古本市」",
        detail: guideDetail({
          group: "図書委員会",
          classification: "展示",
          title: "古本市",
          room: "図書室",
          page: "22ページ",
        }),
      }),
      point({
        id: "multipurpose-2",
        label: "多目的室2",
        category: "exhibition",
        area: area(357, 269, 88, 58),
        summary: "育明生団体「帰国生滞在国紹介」",
        detail: guideDetail({
          group: "育明生団体",
          classification: "展示",
          title: "帰国生滞在国紹介",
          room: "多目的室2",
          page: "21ページ",
        }),
      }),
      point({
        id: "pta-corner",
        label: "PTAコーナー",
        category: "info",
        area: area(357, 335, 88, 60),
        summary: "PTA休憩室・ひのミラ",
        detail: multiGuideDetail([
          {
            group: "PTA",
            classification: "その他",
            title: "PTA休憩室",
            room: "PTAコーナー",
            page: "22ページ",
          },
          {
            group: "ひのミラ",
            classification: "展示",
            title: "日野の未来を見つめて",
            room: "PTAコーナー付近",
            page: "21ページ",
          },
        ]),
      }),
      point({
        id: "3-8",
        label: "3-8",
        category: "event",
        area: area(59, 420, 54, 50),
        summary: "3年8組「ドラゴン桜」",
        detail: guideDetail({
          group: "3年8組",
          classification: "演劇",
          title: "ドラゴン桜",
          room: "3-8",
          page: "17ページ",
        }),
      }),
      point({
        id: "3-7",
        label: "3-7",
        category: "event",
        area: area(109, 420, 54, 50),
        summary: "3年7組 演劇企画",
        detail: guideDetail({
          group: "3年7組",
          classification: "演劇",
          title: "クラス演劇",
          room: "3-7",
          page: "17ページ",
        }),
      }),
      point({
        id: "3-6",
        label: "3-6",
        category: "event",
        area: area(160, 420, 54, 50),
        summary: "3年6組「水平線の歩き方」",
        detail: guideDetail({
          group: "3年6組",
          classification: "演劇",
          title: "水平線の歩き方",
          room: "3-6",
          page: "17ページ",
        }),
      }),
      point({
        id: "3-5",
        label: "3-5",
        category: "event",
        area: area(212, 420, 54, 50),
        summary: "3年5組「寸劇家族」",
        detail: guideDetail({
          group: "3年5組",
          classification: "演劇",
          title: "寸劇家族",
          room: "3-5",
          page: "17ページ",
        }),
      }),
      point({
        id: "3-4",
        label: "3-4",
        category: "event",
        area: area(301, 420, 54, 50),
        summary: "3年4組 演劇企画",
        detail: guideDetail({
          group: "3年4組",
          classification: "演劇",
          title: "クラス演劇",
          room: "3-4",
          page: "16ページ",
        }),
      }),
      point({
        id: "3-3",
        label: "3-3",
        category: "event",
        area: area(353, 420, 54, 50),
        summary: "3年3組「百万年ピクニック」",
        detail: guideDetail({
          group: "3年3組",
          classification: "演劇",
          title: "百万年ピクニック",
          room: "3-3",
          page: "16ページ",
        }),
      }),
      point({
        id: "3-2",
        label: "3-2",
        category: "event",
        area: area(406, 420, 54, 50),
        summary: "3年2組「3年A組―今から皆さんは人質です―」",
        detail: guideDetail({
          group: "3年2組",
          classification: "演劇",
          title: "3年A組―今から皆さんは人質です―",
          room: "3-2",
          page: "16ページ",
        }),
      }),
      point({
        id: "3-1",
        label: "3-1",
        category: "event",
        area: area(459, 420, 54, 50),
        summary: "3年1組「100LIFE」",
        detail: guideDetail({
          group: "3年1組",
          classification: "演劇",
          title: "100LIFE",
          room: "3-1",
          page: "16ページ",
        }),
      }),
    ],
  },
  {
    id: "3F",
    label: "3階",
    headline: "特別教室と2年企画のフロア",
    description:
      "美術室・音楽室・社会科室・生物室などの特別教室と、2-1 から 2-8 の企画を地図から直接選択できます。",
    imageUrl: new URL("../assets/floors/3F.png", import.meta.url).href,
    dimensions: { width: 592, height: 506 },
    anchor: { x: 292, y: 258 },
    slabColor: "#b8d8c9",
    points: [
      point({
        id: "art-room",
        label: "美術室",
        category: "exhibition",
        area: area(112, 96, 116, 72),
        summary: "美術部「レストラン『海の庭』」",
        detail: guideDetail({
          group: "美術部",
          classification: "展示",
          title: "レストラン『海の庭』",
          room: "美術室",
          page: "19ページ",
        }),
      }),
      point({
        id: "music-room",
        label: "音楽室",
        category: "event",
        area: area(112, 188, 116, 78),
        summary: "コーラス部「The autumn concert」",
        detail: guideDetail({
          group: "コーラス部",
          classification: "パフォーマンス",
          title: "The autumn concert",
          room: "音楽室",
          page: "19ページ",
        }),
      }),
      point({
        id: "social-room",
        label: "社会科室",
        category: "event",
        area: area(112, 298, 116, 92),
        summary: "2年3組「呪怨の館」",
        detail: guideDetail({
          group: "2年3組",
          classification: "お化け屋敷",
          title: "呪怨の館",
          room: "社会科室",
          page: "14ページ",
        }),
      }),
      point({
        id: "biology-room",
        label: "生物室",
        category: "exhibition",
        area: area(379, 182, 88, 74),
        summary: "生物部 生きもの図鑑展示",
        detail: guideDetail({
          group: "生物部",
          classification: "展示",
          title: "生きもの図鑑展示",
          room: "生物室",
          page: "20ページ",
        }),
      }),
      point({
        id: "central-stairs-gallery",
        label: "中央階段",
        category: "exhibition",
        area: area(268, 359, 60, 54),
        summary: "選択美術「大切なもの」",
        detail: guideDetail({
          group: "選択美術",
          classification: "展示",
          title: "日本画展示『大切なもの』",
          room: "中央階段",
          page: "22ページ",
        }),
      }),
      point({
        id: "corridor-gallery",
        label: "渡り廊下下",
        category: "exhibition",
        area: area(294, 414, 90, 42),
        summary: "渡り廊下下の展示",
        detail: multiGuideDetail(
          [
            {
              group: "文芸創作会",
              classification: "展示",
              title: "同好会誌配布",
              room: "渡り廊下下付近",
              page: "20ページ",
            },
            {
              group: "選択書道",
              classification: "展示",
              title: "日野台書道展",
              room: "渡り廊下下",
              page: "22ページ",
            },
            {
              group: "文芸",
              classification: "展示",
              title: "作品展示・配布など",
              room: "渡り廊下下★",
            },
          ],
          "パンフレットの展示欄に掲載されている通路展示をまとめています。",
        ),
      }),
      point({
        id: "2-8",
        label: "2-8",
        category: "event",
        area: area(62, 410, 56, 50),
        summary: "2年8組「シンカイ2万マイル」",
        detail: guideDetail({
          group: "2年8組",
          classification: "アミューズメント",
          title: "シンカイ2万マイル",
          room: "2-8",
          page: "15ページ",
        }),
      }),
      point({
        id: "2-7",
        label: "2-7",
        category: "food",
        area: area(117, 410, 56, 50),
        summary: "2年7組「ohana cafe」",
        detail: guideDetail({
          group: "2年7組",
          classification: "食品",
          title: "ohana cafe",
          room: "2-7",
          page: "15ページ",
        }),
      }),
      point({
        id: "2-6",
        label: "2-6",
        category: "exhibition",
        area: area(173, 410, 56, 50),
        summary: "写真部「涼」",
        detail: guideDetail({
          group: "写真部",
          classification: "展示",
          title: "涼",
          room: "2-6",
          page: "19ページ",
        }),
      }),
      point({
        id: "2-5",
        label: "2-5",
        category: "event",
        area: area(229, 410, 56, 50),
        summary: "2年5組 アミューズメント",
        detail: guideDetail({
          group: "2年5組",
          classification: "アミューズメント",
          title: "絶望の迷宮を突破せよ",
          room: "2-5",
          page: "15ページ",
        }),
      }),
      point({
        id: "2-4",
        label: "2-4",
        category: "event",
        area: area(366, 410, 56, 50),
        summary: "2年4組「サウンドの亡霊」",
        detail: guideDetail({
          group: "2年4組",
          classification: "アミューズメント",
          title: "サウンドの亡霊",
          room: "2-4",
          page: "14ページ",
        }),
      }),
      point({
        id: "2-3-normal",
        label: "2-3",
        category: "exhibition",
        area: area(422, 410, 56, 50),
        summary: "将棋部「僕たちに勝つなんて将棋かい!?」",
        detail: guideDetail({
          group: "将棋部",
          classification: "展示",
          title: "僕たちに勝つなんて将棋かい!?",
          room: "2-3",
          page: "20ページ",
        }),
      }),
      point({
        id: "2-2",
        label: "2-2",
        category: "food",
        area: area(478, 410, 56, 50),
        summary: "2年2組「Vintage Diner」",
        detail: guideDetail({
          group: "2年2組",
          classification: "食品",
          title: "Vintage Diner",
          room: "2-2",
          page: "14ページ",
        }),
      }),
      point({
        id: "2-1",
        label: "2-1",
        category: "event",
        area: area(534, 410, 56, 50),
        summary: "2年1組「マーダーミステリー」",
        detail: guideDetail({
          group: "2年1組",
          classification: "アミューズメント",
          title: "マーダーミステリー",
          room: "2-1",
          page: "14ページ",
        }),
      }),
    ],
  },
  {
    id: "4F",
    label: "4階",
    headline: "1年企画と屋上休憩スペース",
    description:
      "1-1 から 1-8 の企画教室と、屋上休憩スペースを地図から直接選択できます。",
    imageUrl: new URL("../assets/floors/4F.png", import.meta.url).href,
    dimensions: { width: 616, height: 618 },
    anchor: { x: 303, y: 349 },
    slabColor: "#d1b2e5",
    points: [
      point({
        id: "roof-west",
        label: "屋上休憩スペース 西",
        category: "lounge",
        area: area(179, 198, 118, 152),
        labelOffset: { x: -2.2, y: 1.32, z: 0 },
        summary: "屋上休憩スペース",
        detail: guideDetail({
          group: "文化祭本部",
          classification: "休憩",
          title: "屋上休憩スペース",
          room: "屋上休憩スペース 西",
          note: "11時から13時まで開放予定です。",
        }),
      }),
      point({
        id: "roof-east",
        label: "屋上休憩スペース 東",
        category: "lounge",
        area: area(399, 198, 118, 152),
        summary: "屋上休憩スペース",
        detail: guideDetail({
          group: "文化祭本部",
          classification: "休憩",
          title: "屋上休憩スペース",
          room: "屋上休憩スペース 東",
          note: "混雑時の分散利用に向いています。",
        }),
      }),
      point({
        id: "1-8",
        label: "1-8",
        category: "event",
        area: area(56, 489, 60, 52),
        summary: "1年8組「カジノ〜麻ベガス〜」",
        detail: guideDetail({
          group: "1年8組",
          classification: "アミューズメント",
          title: "カジノ〜麻ベガス〜",
          room: "1-8",
          page: "13ページ",
        }),
      }),
      point({
        id: "1-7",
        label: "1-7",
        category: "event",
        area: area(116, 489, 60, 52),
        summary: "1年7組「名探偵マイコナン」",
        detail: guideDetail({
          group: "1年7組",
          classification: "アミューズメント",
          title: "名探偵マイコナン",
          room: "1-7",
          page: "13ページ",
        }),
      }),
      point({
        id: "1-6",
        label: "1-6",
        category: "food",
        area: area(177, 489, 60, 52),
        summary: "1年6組「石田珈琲」",
        detail: guideDetail({
          group: "1年6組",
          classification: "食品",
          title: "石田珈琲",
          room: "1-6",
          page: "13ページ",
        }),
      }),
      point({
        id: "1-5",
        label: "1-5",
        category: "event",
        area: area(238, 489, 60, 52),
        summary: "1年5組「放課後、誰もいないはずの教室で。」",
        detail: guideDetail({
          group: "1年5組",
          classification: "アミューズメント",
          title: "放課後、誰もいないはずの教室で。",
          room: "1-5",
          page: "13ページ",
        }),
      }),
      point({
        id: "1-4",
        label: "1-4",
        category: "event",
        area: area(378, 489, 60, 52),
        labelOffset: { x: -0.3, y: 1.32, z: -1.05 },
        summary: "1年4組 アミューズメント",
        detail: guideDetail({
          group: "1年4組",
          classification: "アミューズメント",
          title: "クラス企画",
          room: "1-4",
          page: "12ページ",
        }),
      }),
      point({
        id: "1-3",
        label: "1-3",
        category: "food",
        area: area(439, 489, 60, 52),
        labelOffset: { x: -0.1, y: 1.32, z: -1.2 },
        summary: "1年3組「ご主人様にお給仕します♡」",
        detail: guideDetail({
          group: "1年3組",
          classification: "食品",
          title: "ご主人様にお給仕します♡",
          room: "1-3",
          page: "12ページ",
        }),
      }),
      point({
        id: "1-2",
        label: "1-2",
        category: "event",
        area: area(500, 489, 60, 52),
        labelOffset: { x: 0.1, y: 1.32, z: -1.05 },
        summary: "1年2組「合法! オフラインカジノ」",
        detail: guideDetail({
          group: "1年2組",
          classification: "アミューズメント",
          title: "合法! オフラインカジノ",
          room: "1-2",
          page: "12ページ",
        }),
      }),
      point({
        id: "1-1",
        label: "1-1",
        category: "event",
        area: area(561, 489, 60, 52),
        labelOffset: { x: 0.32, y: 1.32, z: -1.2 },
        summary: "1年1組「手品師 カジノ」",
        detail: guideDetail({
          group: "1年1組",
          classification: "アミューズメント",
          title: "手品師 カジノ",
          room: "1-1",
          page: "12ページ",
        }),
      }),
    ],
  },
];
